### ISSUE TITLE
GCM push message content

### ISSUE THREAD

**Issue by Calrama** [WhisperSystems/libtextsecure-java#15]
Hello, according to [this API document](https://github.com/WhisperSystems/TextSecure-Server/wiki/API-Protocol), a push message received via GCM should contain an encrypted payload. However, what I receive is the following message:
```JSON
{"collapseKey":"do_not_collapse","data":{"notification":""},"from":"312334754206"}
```
I would like to know if this is expected?

**Comment by moxie0** [comment]
Yeah, that's correct. We've migrated to only sending connect notifications, which are indications that you should connect to retrieve messages.

**Comment by Calrama** [comment]
Thank you for the clarification. Would it be possible to have the API document be updated to the current implementation (or is there a different specification document I overlooked)?
