### ISSUE TITLE
Leaks contact phone numbers to device log (Signal for Android)

### ISSUE THREAD

**Issue by lorenzhs** [WhisperSystems/libtextsecure-java#18]
`W/PushServiceSocket(14346): Opening URL: https://textsecure-service.whispersystems.org/v1/messages/+49[REDACTED]/1449516470728`

The phone number is not my own.

https://github.com/WhisperSystems/libtextsecure-java/blob/432ffbaa3a2eeb100ca1fa6470d2243a64e6c913/java/src/main/java/org/whispersystems/textsecure/internal/push/PushServiceSocket.java#L568

See also https://github.com/WhisperSystems/Signal-Android/issues/4832

**Comment by moxie0** [comment]
Thanks @lorenzhs but it's not necessary to open duplicate issues.
