### ISSUE TITLE
Missing Documentation: How to create a QR code

### ISSUE THREAD

**Issue by Turakar** [WhisperSystems/libtextsecure-java#20]
Hello,

I'm trying to figure out how to create a QR code which can be read by the android app. I fount out the basic syntax ("tsdevice:/?"), but I have questions regarding the two parameters:

- uuid
- pub_key (Base64 encoded identityKeyPair.getPublicKey()?)

The thing which makes this an issue and not just a support request is the lack of documentation for this library. Actually there is pretty much no documentation, and the documentation in the readme uses undefined method names and some magic variables nobody knows what is inside.

However, I want to say thanks for open-sourcing this library ;)

Best Regards,
Turakar

**Comment by Turakar** [comment]
Ok, I found out how to do that by now. As far as I understood the library, the java version does not yet support registering as a second device. I'm going to start working on that in a fork in a few days.

**Comment by moxie0** [comment]
sorry this is not a discussion forum
