### ISSUE TITLE
Use Flags instead of uint32 for DataMessage flags field

### ISSUE THREAD

**Issue by janimo** [WhisperSystems/libtextsecure-java#9]
the Flags enum type in the .proto file seems unused

**Comment by liliakai** [comment]
It's conceivable that we might add more flags in the future. Using the Flags type directly would allow only one flag value per DataMessage. Use of a unit32 for the flags field allows multiple flags to be bitmasked in. Consumers of libtextsecure must reference this enum to parse those flags.

**Comment by janimo** [comment]
that makes sense, thanks for the explanation. I was mislead by the presence of the apparently unused Flags type.
